backend:
  #name: github # this should be uncommented in production
  #repo: sslotsky/me
  name: test-repo #added this to test locally with netlify cms(in prod this should not exist)

media_folder: static/assets
public_folder: assets

collections:
  - name: projects
    label: Projects
    folder: /content/projects # adjusted the folder to match config. Should any more items need to be added this config should be updated
    create: true
    fields:
      - { name: title, label: Title }
      - { name: url, label: URL }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
