backend:
  name: github
  repo: sslotsky/me

media_folder: content/assets
public_folder: assets

collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: url, label: URL }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: slug, label: Slug }
      - { name: body, label: Body, widget: markdown }
